name: Backport all Pull request
description: Backport all kind of pull request by adding a label
branding:
  icon: corner-left-down
  color: blue
inputs:
  token:
    default: ${{ github.token }}
runs:
  using: 'docker'
  image: 'Dockerfile'
